#!/bin/bash

TARGET="/home/atebites/bot"      # the directory where the files need to be deployed
GIT_DIR="/home/atebites/bot.git" # the current git bare repository path
BRANCH="production"              # the branch to deploy (default to `production`)

while read oldrev newrev ref; do
        # only checking out the branch to deploy
        if [[ $ref = refs/heads/$BRANCH ]]; then
                echo "Ref '$ref' received."

                if [ ! -d "$TARGET" ]; then
                        echo "'${TARGET}' dir is missing, creating it"
                        mkdir -p $TARGET
                fi

                echo "Deploying '${BRANCH}' branch to production"
                git --work-tree=$TARGET --git-dir=$GIT_DIR checkout --force $BRANCH

                echo "Installing package..."
                pip install -U $TARGET

                exit 0
        else
                echo "You pushed '$ref' branch,"
                echo "but you set '${BRANCH}' branch as deploy branch."
                echo "Exiting without error."

                exit 0
        fi
done

